<link rel="stylesheet" href="work/resources/css/reset.css" type="text/css"
	media="screen" />
<link rel="stylesheet" href="work/resources/css/style.css" type="text/css"
	media="screen" />
<link rel="stylesheet" href="work/resources/css/invalid.css" type="text/css"
	media="screen" />

<!--                       Javascripts                       -->

<!--                       Javascripts                       -->
<!-- jQuery -->
<script type="text/javascript"
	src="work/jquery-validation-1.16.0\lib\jquery.js"></script>

<!-- jQuery Configuration -->
<script type="text/javascript"
	src="resources/scripts/simpla.jquery.configuration.js"></script>
<!-- Facebox jQuery Plugin -->
<script type="text/javascript" src="resources/scripts/facebox.js"></script>

<!-- jQuery WYSIWYG Plugin -->
<script type="text/javascript" src="resources/scripts/jquery.wysiwyg.js"></script>

<!-- jQuery Datepicker Plugin -->
<script type="text/javascript"
	src="resources/scripts/jquery.datePicker.js"></script>
<script type="text/javascript" src="resources/scripts/jquery.date.js"></script>

<script type="text/javascript" src="work/jquery-validation-1.16.0\dist\jquery.validate.js"></script>

